apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-default
spec:
  hard:
    pods: "20"
    requests.cpu: "1000m"
    requests.memory: 2Gi
    limits.cpu: "1000m"
    limits.memory: 2Gi
    configmaps: "5"
    persistentvolumeclaims: "5"
    replicationcontrollers: "10"
    secrets: "3"
    services: "10"
    services.loadbalancers: "1"
